window.QUIZ_PLAYER_FILES = [
  {id:"shuto",name:"周東 佑京",team:"福岡ソフトバンクホークス",role:"外野手",meta:"右投左打｜2017 育成2位",hook:"まず『足』。そこから育成出身までつなげる。",remember:"俊足・盗塁が大きな武器。育成選手ドラフトから一軍主力へ上がった経歴も、ホークスの育成文化とセットで覚えたい。",quizId:"c13",source:"https://npb.jp/bis/players/21925136.html",league:"NPB"},
  {id:"kondo",name:"近藤 健介",team:"福岡ソフトバンクホークス",role:"外野手",meta:"左打｜出塁能力",hook:"打率だけでなく『塁に出る人』。",remember:"高い打撃技術に加え、出塁率で価値を捉えると選手像がつかみやすい。",quizId:"c14",source:"https://npb.jp/bis/players/search/result?search_keyword=%E8%BF%91%E8%97%A4%E3%80%80%E5%81%A5%E4%BB%8B",league:"NPB"},
  {id:"miyagi",name:"宮城 大弥",team:"オリックス・バファローズ",role:"投手",meta:"左投左打｜2019 ドラフト1位",hook:"オリックスの左の軸。",remember:"興南高からドラフト1位。左腕の先発投手として覚えると、山本由伸後のオリックス投手陣を見る入口になる。",quizId:"c15",source:"https://npb.jp/bis/players/71875151.html",league:"NPB"},
  {id:"morishita",name:"森下 翔太",team:"阪神タイガース",role:"外野手",meta:"右投右打｜2022 ドラフト1位",hook:"阪神の右の長打。",remember:"東海大相模高、中央大を経て阪神へ。右打ち外野手・ドラフト1位という骨格を先に覚える。",quizId:"c16",source:"https://npb.jp/bis/players/43145157.html",league:"NPB"},
  {id:"mannami",name:"万波 中正",team:"北海道日本ハムファイターズ",role:"外野手",meta:"右投右打｜長打力",hook:"強肩とパワーで覚える。",remember:"大型外野手で長打力が特徴。日本ハムの若い野手陣を覚えるときの中心人物の一人。",quizId:"c17",source:"https://npb.jp/bis/players/11815138.html",league:"NPB"},
  {id:"sato",name:"佐藤 輝明",team:"阪神タイガース",role:"内野手",meta:"右投左打｜2020 ドラフト1位",hook:"左の長距離砲。",remember:"近畿大からドラフト1位で阪神入り。まず長打力、その次に左打ちの内野手として整理。",quizId:"c10",source:"https://npb.jp/bis/players/41045153.html",league:"NPB"},
  {id:"takahashi",name:"髙橋 宏斗",team:"中日ドラゴンズ",role:"投手",meta:"右投右打｜2020 ドラフト1位",hook:"中日の若いエース格。",remember:"中京大中京高からドラフト1位。中日の投手陣を覚える入口として押さえたい右腕。",quizId:"c11",source:"https://npb.jp/bis/players/61265153.html",league:"NPB"},
  {id:"kiyomiya",name:"清宮 幸太郎",team:"北海道日本ハムファイターズ",role:"内野手",meta:"右投左打｜長距離打者",hook:"早実から日本ハムへ。",remember:"高校時代から注目された左の長距離打者。日本ハムの野手を万波と並べて覚えると整理しやすい。",quizId:"c06",source:"https://npb.jp/announcement/2026/registered_f.html",league:"NPB"},
  {id:"yanagita",name:"柳田 悠岐",team:"福岡ソフトバンクホークス",role:"外野手",meta:"右投左打｜強打",hook:"ホークスの強打者の象徴。",remember:"高い身体能力と強い打球で知られる外野手。近藤・周東と役割の違いを並べると覚えやすい。",quizId:"c07",source:"https://npb.jp/announcement/2026/registered_h.html",league:"NPB"},
  {id:"ohtani",name:"大谷 翔平",team:"ロサンゼルス・ドジャース",role:"投手／指名打者",meta:"NPB：日本ハム",hook:"二刀流。NPBからMLBへの線で覚える。",remember:"北海道日本ハムからMLBへ。所属だけでなく、投打の両方でプレーする選手像を中心に。",quizId:"m01",source:"https://www.mlb.com/player/shohei-ohtani-660271",league:"MLB"},
  {id:"yamamoto",name:"山本 由伸",team:"ロサンゼルス・ドジャース",role:"投手",meta:"NPB：オリックス",hook:"オリックスのエースからドジャースへ。",remember:"NPB時代のオリックスとMLBのドジャースを一本の線で結ぶと、移籍後も記憶に残りやすい。",quizId:"m13",source:"https://www.mlb.com/player/yoshinobu-yamamoto-808967",league:"MLB"},
  {id:"sasaki",name:"佐々木 朗希",team:"ロサンゼルス・ドジャース",role:"投手",meta:"NPB：千葉ロッテ",hook:"ロッテからドジャースへ。",remember:"NPBでは千葉ロッテ。山本由伸と同じドジャースでも、NPB時代の所属を分けて覚える。",quizId:"m03",source:"https://www.mlb.com/player/roki-sasaki-808963",league:"MLB"},
  {id:"imanaga",name:"今永 昇太",team:"シカゴ・カブス",role:"投手",meta:"NPB：横浜DeNA",hook:"DeNAからカブスへ。",remember:"左腕投手。MLB所属だけでなく、NPBでは横浜DeNAだったことまでセットで覚える。",quizId:"m04",source:"https://www.mlb.com/player/shota-imanaga-684007",league:"MLB"},
  {id:"suzuki",name:"鈴木 誠也",team:"シカゴ・カブス",role:"外野手",meta:"NPB：広島",hook:"広島の主軸からカブスへ。",remember:"今永と同じカブス。『投手＝今永、打者＝鈴木』で対にすると所属を覚えやすい。",quizId:"m05",source:"https://www.mlb.com/player/seiya-suzuki-673548",league:"MLB"},
  {id:"senga",name:"千賀 滉大",team:"ニューヨーク・メッツ",role:"投手",meta:"NPB：ソフトバンク｜育成出身",hook:"育成からMLBへ。",remember:"ソフトバンクで育成選手から主力投手へ成長し、MLBへ。周東と並べるとホークスの育成文脈も見えてくる。",quizId:"m06",source:"https://www.mlb.com/player/kodai-senga-673540",league:"MLB"}
];
